[package]
name = "livetop"
version = "0.1.0"
edition = "2024"

[dependencies]
ab_glyph = "0.2.32"
anyhow = "1.0.104"
dirs = "6.0.0"
eframe = "0.36.1"
egui = "0.36.1"
libloading = "0.9.0"
log = "0.4.33"
muda = "0.19.3"
rfd = "0.17.2"
serde = { version = "1.0.229", features = ["derive"] }
thiserror = "2.0.20"
toml = "1.1.4"
tray-icon = "0.24.2"
windows = { version = "0.62.2", features = ["Win32_Foundation", "Win32_UI_WindowsAndMessaging", "Win32_Graphics_Gdi", "Win32_System_LibraryLoader", "Win32_System_Threading", "Win32_UI_HiDpi"] }
winreg = "0.56.0"
